export const mockDonationRequests = [
  {
    donationId: 'd1a2b3c4',
    patientId: 'p12345',
    requestName: 'John Doe - Urgent Chemotherapy',
    expectedDate: '2025-04-10',
    description: 'Need chemotherapy medication for my second cycle.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/d1a2b3c4',
    createdAt: '2025-03-20',
    updatedAt: '2025-03-21',
    items: [
      { medicine: 'Cisplatin', amount: '2 vials' },
      { medicine: 'Doxorubicin', amount: '1 vial' },
    ],
  },
  {
    donationId: 'e5f6g7h8',
    patientId: 'p67890',
    requestName: 'Alice Smith - Cancer Surgery',
    expectedDate: '2025-05-01',
    description: 'Seeking financial support for a major surgery.',
    status: 'Approved',
    qrCodeUrl: 'https://example.com/qrcode/e5f6g7h8',
    createdAt: '2025-03-15',
    updatedAt: '2025-03-18',
    items: [{ medicine: 'General Surgery Costs', amount: '$5000' }],
  },
  {
    donationId: 'i9j0k1l2',
    patientId: 'p11223',
    requestName: 'David Johnson - Post-Treatment Support',
    expectedDate: '2025-04-20',
    description: 'Need funds for post-treatment medications and care.',
    status: 'Rejected',
    qrCodeUrl: 'https://example.com/qrcode/i9j0k1l2',
    createdAt: '2025-03-18',
    updatedAt: '2025-03-19',
    items: [{ medicine: 'Pain Management Kit', amount: '3 packs' }],
  },
  {
    donationId: 'm3n4o5p6',
    patientId: 'p33445',
    requestName: 'Emily Brown - Radiation Therapy',
    expectedDate: '2025-06-05',
    description: 'Requesting assistance for radiation treatment costs.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/m3n4o5p6',
    createdAt: '2025-03-25',
    updatedAt: '2025-03-26',
    items: [{ medicine: 'Radiation Session', amount: '10 sessions' }],
  },
  {
    donationId: 'q7r8s9t0',
    patientId: 'p55667',
    requestName: 'Michael Wilson - Palliative Care Support',
    expectedDate: '2025-04-15',
    description: 'Seeking funds for palliative care and comfort medicines.',
    status: 'Completed',
    qrCodeUrl: 'https://example.com/qrcode/q7r8s9t0',
    createdAt: '2025-03-12',
    updatedAt: '2025-03-14',
    items: [{ medicine: 'Morphine Tablets', amount: '30 tablets' }],
  },
  {
    donationId: 'u1v2w3x4',
    patientId: 'p78901',
    requestName: 'Sarah Johnson - Leukemia Treatment',
    expectedDate: '2025-07-20',
    description: 'Need help covering the cost of bone marrow transplant.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/u1v2w3x4',
    createdAt: '2025-03-28',
    updatedAt: '2025-03-29',
    items: [{ medicine: 'Bone Marrow Transplant', amount: '$20,000' }],
  },
  {
    donationId: 'y5z6a7b8',
    patientId: 'p23456',
    requestName: 'Liam Thompson - Post-Surgery Recovery',
    expectedDate: '2025-05-15',
    description: 'Raising funds for rehabilitation and medicines post-surgery.',
    status: 'Approved',
    qrCodeUrl: 'https://example.com/qrcode/y5z6a7b8',
    createdAt: '2025-03-10',
    updatedAt: '2025-03-12',
    items: [
      { medicine: 'Physical Therapy', amount: '10 sessions' },
      { medicine: 'Painkillers', amount: '2 bottles' },
    ],
  },
  {
    donationId: 'c9d0e1f2',
    patientId: 'p67892',
    requestName: 'Sophia White - Chemotherapy Cycle 3',
    expectedDate: '2025-08-10',
    description: 'Requesting financial aid for the next chemotherapy cycle.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/c9d0e1f2',
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
    items: [{ medicine: 'Paclitaxel', amount: '3 vials' }],
  },
  {
    donationId: 'g3h4i5j6',
    patientId: 'p88990',
    requestName: 'Olivia Martin - Pediatric Cancer Support',
    expectedDate: '2025-06-30',
    description: 'Fundraising for pediatric cancer treatment and medications.',
    status: 'Rejected',
    qrCodeUrl: 'https://example.com/qrcode/g3h4i5j6',
    createdAt: '2025-03-17',
    updatedAt: '2025-03-18',
    items: [{ medicine: 'Pediatric Chemotherapy Drugs', amount: '5 doses' }],
  },
  {
    donationId: 'k7l8m9n0',
    patientId: 'p33499',
    requestName: 'Ethan Brown - Tumor Surgery Assistance',
    expectedDate: '2025-09-01',
    description: 'Need urgent funds for a life-saving tumor removal surgery.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/k7l8m9n0',
    createdAt: '2025-03-30',
    updatedAt: '2025-03-31',
    items: [{ medicine: 'Surgery Cost', amount: '$10,000' }],
  },
];

export const mockDonationTableData = [
  {
    donationId: 'd1a2b3c4',
    requestName: 'Urgent Chemotherapy',
    expectedDate: '2025-04-10',
    status: 'Pending',
    createdAt: '2025-03-20',
  },
  {
    donationId: 'e5f6g7h8',
    requestName: ' Cancer Surgery',
    expectedDate: '2025-05-01',
    status: 'Approved',
    createdAt: '2025-03-15',
  },
  {
    donationId: 'i9j0k1l2',
    requestName: 'Post-Treatment Support',
    expectedDate: '2025-04-20',
    status: 'Rejected',
    createdAt: '2025-03-18',
  },
  {
    donationId: 'm3n4o5p6',
    requestName: 'Radiation Therapy',
    expectedDate: '2025-06-05',
    status: 'Pending',
    createdAt: '2025-03-25',
  },
  {
    donationId: 'q7r8s9t0',
    requestName: 'Palliative Care Support',
    expectedDate: '2025-04-15',
    status: 'Completed',
    createdAt: '2025-03-12',
  },
];

const extendedMockDonationTableData = [
  {
    donationId: 'd1a2b3c4',
    patientId: 'p12345',
    requestName: 'John Doe - Urgent Chemotherapy',
    expectedDate: '2025-04-10',
    description: 'Need chemotherapy medication for my second cycle.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/d1a2b3c4',
    createdAt: '2025-03-20',
    updatedAt: '2025-03-21',
    items: [
      { medicine: 'Cisplatin', amount: '2 vials' },
      { medicine: 'Doxorubicin', amount: '1 vial' },
    ],
    importer: {
      importerId: 'imp001',
      importerName: 'MediPharm Suppliers',
      acceptedPrice: 'Rs. 1200',
      eta: '2025-04-08',
    },
  },
  {
    donationId: 'e5f6g7h8',
    patientId: 'p67890',
    requestName: 'Alice Smith - Cancer Surgery',
    expectedDate: '2025-05-01',
    description:
      'Financial aid required for surgery and post-recovery expenses.',
    status: 'Approved',
    qrCodeUrl: 'https://example.com/qrcode/e5f6g7h8',
    createdAt: '2025-03-18',
    updatedAt: '2025-03-22',
    items: [
      { medicine: 'General Anesthesia', amount: '1 unit' },
      { medicine: 'Pain Relief Medication', amount: '5 packs' },
    ],
    importer: {
      importerId: 'imp002',
      importerName: 'HealthCare Suppliers',
      acceptedPrice: 'Rs. 9800',
      eta: '2025-04-28',
    },
  },
  {
    donationId: 'i9j0k1l2',
    patientId: 'p54321',
    requestName: 'David Brown - Post-Treatment Support',
    expectedDate: '2025-04-20',
    description: 'Medication and supplements needed for recovery post-chemo.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/i9j0k1l2',
    createdAt: '2025-03-15',
    updatedAt: '2025-03-20',
    items: [
      { medicine: 'Multivitamins', amount: '3 bottles' },
      { medicine: 'Immune Boosters', amount: '2 packs' },
    ],
    importer: {
      importerId: 'imp003',
      importerName: 'Wellness Pharm',
      acceptedPrice: 'Rs. 2700',
      eta: '2025-04-18',
    },
  },
  {
    donationId: 'm3n4o5p6',
    patientId: 'p98765',
    requestName: 'Emma Wilson - Radiation Therapy',
    expectedDate: '2025-06-05',
    description:
      'Funds required for radiation therapy sessions and medication.',
    status: 'Pending',
    qrCodeUrl: 'https://example.com/qrcode/m3n4o5p6',
    createdAt: '2025-03-22',
    updatedAt: '2025-03-23',
    items: [
      { medicine: 'Radiation Shield', amount: '1 unit' },
      { medicine: 'Anti-Nausea Tablets', amount: '10 strips' },
    ],
    importer: {
      importerId: 'imp004',
      importerName: 'OncoMed Distributors',
      acceptedPrice: 'Rs. 6800',
      eta: '2025-06-01',
    },
  },
  {
    donationId: 'q7r8s9t0',
    patientId: 'p24680',
    requestName: 'Sophia Green - Palliative Care Support',
    expectedDate: '2025-04-15',
    description:
      'Pain relief and support medications needed for end-stage care.',
    status: 'Approved',
    qrCodeUrl: 'https://example.com/qrcode/q7r8s9t0',
    createdAt: '2025-03-10',
    updatedAt: '2025-03-18',
    items: [
      { medicine: 'Morphine', amount: '3 vials' },
      { medicine: 'Sedatives', amount: '2 packs' },
    ],
    importer: {
      importerId: 'imp005',
      importerName: 'CareFirst Medics',
      acceptedPrice: 'Rs. 2200',
      eta: '2025-04-12',
    },
  },
];
